In [33]:
import numpy as np
from scipy import stats
matrix=np.array([[1,2,3],[1,1,4],[5,2,4]])
print(matrix)
mean=np.mean(matrix)
median=np.median(matrix)
print ("The Mean of a matrix is:",mean)
print ("The median of a matrix is:",median)
mode=stats.mode(matrix,axis=0)
print ("The mode of a matrix is:",mode)
transpose=np.transpose(matrix)
print ("The transpose of a matrix is:",transpose)

[[1 2 3]
 [1 1 4]
 [5 2 4]]
The Mean of a matrix is: 2.5555555555555554
The median of a matrix is: 2.0
The mode of a matrix is: ModeResult(mode=array([1, 2, 4], dtype=int64), count=array([2, 2, 2], dtype=int64))
The transpose of a matrix is: [[1 1 5]
 [2 1 2]
 [3 4 4]]


In [34]:
print("original matrix:",matrix)
inverse_matrix= np.linalg.inv(matrix)
print("Inverse of matrix is:",inverse_matrix)

original matrix: [[1 2 3]
 [1 1 4]
 [5 2 4]]
Inverse of matrix is: [[-0.21052632 -0.10526316  0.26315789]
 [ 0.84210526 -0.57894737 -0.05263158]
 [-0.15789474  0.42105263 -0.05263158]]


In [35]:
print("original matrix:",matrix)
det_A = np.linalg.det(matrix)
print("Determinant of matrix:", det_A)

original matrix: [[1 2 3]
 [1 1 4]
 [5 2 4]]
Determinant of matrix: 18.999999999999996


In [ ]:
https://byjus.com/maths/inverse-matrix/     #inverse matrix reference