In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [28]:
#step 1: create some sample data
data = np.random.rand(100,10)
np.set_printoptions(precision=4, suppress=True)
print("Formated Array:")
print(data)

Formated Array:
[[0.0751 0.0906 0.4859 0.9945 0.5183 0.111  0.6863 0.0408 0.6288 0.7101]
 [0.236  0.0839 0.1604 0.1707 0.9953 0.7892 0.6687 0.9056 0.3618 0.981 ]
 [0.3033 0.8881 0.2428 0.1871 0.7249 0.6594 0.1396 0.5408 0.4531 0.4223]
 [0.2713 0.2731 0.0367 0.7575 0.8221 0.41   0.0861 0.2148 0.0278 0.077 ]
 [0.4158 0.0125 0.1433 0.6367 0.1927 0.3382 0.2187 0.9006 0.3424 0.7669]
 [0.6083 0.7478 0.188  0.1354 0.3337 0.7126 0.5092 0.6487 0.98   0.0104]
 [0.5462 0.5886 0.5665 0.1206 0.5209 0.9235 0.6441 0.3694 0.9036 0.6075]
 [0.8153 0.0383 0.7303 0.2154 0.5118 0.7514 0.7654 0.5964 0.6892 0.0367]
 [0.5325 0.0188 0.5515 0.6852 0.5753 0.8758 0.3323 0.3967 0.806  0.8556]
 [0.718  0.9102 0.5211 0.676  0.9128 0.3229 0.1954 0.0268 0.5264 0.5754]
 [0.0876 0.5583 0.1443 0.286  0.7819 0.1803 0.7106 0.5121 0.6361 0.4961]
 [0.7739 0.589  0.7941 0.5646 0.9601 0.5591 0.8735 0.2635 0.1298 0.2062]
 [0.1809 0.6979 0.511  0.5538 0.2335 0.009  0.9548 0.1868 0.8308 0.494 ]
 [0.4422 0.9509 0.8146 0.0782 0.698

In [29]:
#step 2: standerdize the data
mean= np.mean(data,axis=0)
std_dev=np.std(data,axis=0)
std_data=(data-mean)/std_dev
mean1=np.mean(std_data,axis=0)
std_dev1=np.std(std_data,axis=0)
print(mean,std_dev)
print(mean1,std_dev1)
print(std_data)

[0.5035 0.4739 0.4926 0.5169 0.5334 0.4588 0.485  0.4863 0.5209 0.4835] [0.2712 0.2852 0.2843 0.278  0.2729 0.2859 0.3153 0.2699 0.2613 0.2948]
[-0. -0. -0.  0.  0. -0. -0. -0.  0. -0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[-1.5796 -1.344  -0.0235  1.7182 -0.0552 -1.2165  0.6383 -1.6501  0.413
   0.7685]
 [-0.9862 -1.3673 -1.1684 -1.2455  1.6925  1.1552  0.5825  1.5533 -0.609
   1.6873]
 [-0.7384  1.4519 -0.8787 -1.1867  0.7016  0.7012 -1.0955  0.2018 -0.2597
  -0.2078]
 [-0.8561 -0.704  -1.6035  0.8655  1.0581 -0.1707 -1.2652 -1.0056 -1.8875
  -1.3789]
 [-0.3233 -1.6177 -1.2286  0.431  -1.2486 -0.4218 -0.8446  1.5348 -0.6832
   0.961 ]
 [ 0.3862  0.9602 -1.0713 -1.3727 -0.7318  0.8876  0.0766  0.6015  1.7572
  -1.6047]
 [ 0.1573  0.402   0.2602 -1.4257 -0.0457  1.6249  0.5045 -0.433   1.4645
   0.4206]
 [ 1.1496 -1.5274  0.8362 -1.0846 -0.0791  1.0231  0.8892  0.4079  0.6439
  -1.5154]
 [ 0.1069 -1.5955  0.2073  0.6056  0.1534  1.4582 -0.4845 -0.3318  1.0911
   1.2621]
 [ 0.7908  1.5296  

In [30]:
cov_matrix=np.cov(std_data,rowvar=False)
size_cc=cov_matrix.size
shape_cc=cov_matrix.shape
print(size_cc,shape_cc)
print(cov_matrix)

100 (10, 10)
[[ 1.0101  0.0507  0.15    0.0025 -0.0202  0.0065  0.1955  0.1359  0.0271
  -0.1103]
 [ 0.0507  1.0101  0.0961  0.0451 -0.0492 -0.1606  0.1238 -0.1076 -0.1923
  -0.0604]
 [ 0.15    0.0961  1.0101 -0.08    0.02   -0.1152  0.0184 -0.1399  0.0166
   0.0429]
 [ 0.0025  0.0451 -0.08    1.0101  0.0108 -0.247  -0.1076  0.024   0.0476
   0.0977]
 [-0.0202 -0.0492  0.02    0.0108  1.0101  0.2598  0.0426  0.1248 -0.0368
   0.0285]
 [ 0.0065 -0.1606 -0.1152 -0.247   0.2598  1.0101 -0.0726  0.0933 -0.0769
  -0.1118]
 [ 0.1955  0.1238  0.0184 -0.1076  0.0426 -0.0726  1.0101 -0.0238 -0.1205
   0.0374]
 [ 0.1359 -0.1076 -0.1399  0.024   0.1248  0.0933 -0.0238  1.0101  0.0127
   0.0447]
 [ 0.0271 -0.1923  0.0166  0.0476 -0.0368 -0.0769 -0.1205  0.0127  1.0101
  -0.0119]
 [-0.1103 -0.0604  0.0429  0.0977  0.0285 -0.1118  0.0374  0.0447 -0.0119
   1.0101]]


In [31]:
eigenvalues,eigenvectors=np.linalg.eigh(cov_matrix)
print(eigenvalues)
print(eigenvectors)


[0.5182 0.6635 0.747  0.8537 0.9743 1.0663 1.161  1.1893 1.3996 1.5282]
[[-0.3632 -0.3539 -0.3453 -0.0922 -0.0685 -0.1382 -0.3438  0.5485 -0.4027
  -0.1002]
 [ 0.0568 -0.4235  0.5489 -0.0633 -0.3281 -0.2076  0.2667 -0.1213 -0.2927
  -0.4357]
 [ 0.3479  0.2571 -0.0277 -0.2993 -0.3309  0.6115 -0.3218  0.0255 -0.218
  -0.2958]
 [ 0.39   -0.0358 -0.3841  0.2202 -0.436  -0.1833  0.2764  0.3639  0.4106
  -0.2225]
 [-0.3708  0.1592  0.1485  0.4033 -0.4764  0.3558  0.2975  0.162  -0.1948
   0.3825]
 [ 0.5083 -0.4847 -0.1828 -0.0295 -0.0952  0.0364 -0.0074 -0.1918 -0.268
   0.5945]
 [ 0.357   0.1774  0.0195  0.5159  0.4735  0.0409  0.1608  0.2316 -0.4806
  -0.1955]
 [ 0.2124  0.2655  0.3994 -0.4665  0.0494 -0.2115  0.1344  0.5736 -0.0135
   0.336 ]
 [ 0.1243 -0.2685  0.4643  0.4033  0.0205  0.127  -0.5687  0.2307  0.3696
   0.067 ]
 [-0.0887 -0.4401 -0.0148 -0.1988  0.3537  0.583   0.4181  0.2291  0.242
  -0.0883]]


In [32]:
sorted_indices=np.argsort(eigenvalues)[::-1]
eigenvalues=eigenvalues[sorted_indices]
eigenvectors=eigenvectors[:,sorted_indices]
print(eigenvalues)
print(eigenvectors)

[1.5282 1.3996 1.1893 1.161  1.0663 0.9743 0.8537 0.747  0.6635 0.5182]
[[-0.1002 -0.4027  0.5485 -0.3438 -0.1382 -0.0685 -0.0922 -0.3453 -0.3539
  -0.3632]
 [-0.4357 -0.2927 -0.1213  0.2667 -0.2076 -0.3281 -0.0633  0.5489 -0.4235
   0.0568]
 [-0.2958 -0.218   0.0255 -0.3218  0.6115 -0.3309 -0.2993 -0.0277  0.2571
   0.3479]
 [-0.2225  0.4106  0.3639  0.2764 -0.1833 -0.436   0.2202 -0.3841 -0.0358
   0.39  ]
 [ 0.3825 -0.1948  0.162   0.2975  0.3558 -0.4764  0.4033  0.1485  0.1592
  -0.3708]
 [ 0.5945 -0.268  -0.1918 -0.0074  0.0364 -0.0952 -0.0295 -0.1828 -0.4847
   0.5083]
 [-0.1955 -0.4806  0.2316  0.1608  0.0409  0.4735  0.5159  0.0195  0.1774
   0.357 ]
 [ 0.336  -0.0135  0.5736  0.1344 -0.2115  0.0494 -0.4665  0.3994  0.2655
   0.2124]
 [ 0.067   0.3696  0.2307 -0.5687  0.127   0.0205  0.4033  0.4643 -0.2685
   0.1243]
 [-0.0883  0.242   0.2291  0.4181  0.583   0.3537 -0.1988 -0.0148 -0.4401
  -0.0887]]


In [33]:
n_components=5

In [34]:
selected_eigenvectors=eigenvectors[:,:n_components]
print(selected_eigenvectors)

[[-0.1002 -0.4027  0.5485 -0.3438 -0.1382]
 [-0.4357 -0.2927 -0.1213  0.2667 -0.2076]
 [-0.2958 -0.218   0.0255 -0.3218  0.6115]
 [-0.2225  0.4106  0.3639  0.2764 -0.1833]
 [ 0.3825 -0.1948  0.162   0.2975  0.3558]
 [ 0.5945 -0.268  -0.1918 -0.0074  0.0364]
 [-0.1955 -0.4806  0.2316  0.1608  0.0409]
 [ 0.336  -0.0135  0.5736  0.1344 -0.2115]
 [ 0.067   0.3696  0.2307 -0.5687  0.127 ]
 [-0.0883  0.242   0.2291  0.4181  0.583 ]]


In [35]:
final_result=np.dot(std_data,selected_eigenvectors)

In [36]:
print("Final result after PCA:")
print(final_result)

Final result after PCA:
[[-1.095   2.131  -0.3816  0.6272  0.9796]
 [ 2.8697 -0.2164  0.4664  1.8554  1.1799]
 [ 0.9334 -0.3705 -1.3016  0.711  -0.4857]
 [ 0.8822  0.6858 -1.5271  1.336  -1.3872]
 [ 0.8265  1.77    0.7704  0.6867 -0.7948]
 [ 0.8594 -0.6458 -0.3197 -1.7128 -1.7206]
 [ 0.8147 -0.8433 -0.4909 -1.0844  0.9015]
 [ 1.2624 -1.4639  0.4745 -2.2046  0.0259]
 [ 1.3591  1.1527  0.4615 -0.542   1.3647]
 [-1.072  -0.1489 -0.3373  0.4209  0.5137]
 [ 0.2591  0.3686 -0.5442  0.9438 -0.0679]
 [-0.3565 -2.4407  0.0242  0.4791  0.4509]
 [-2.2151  0.671  -0.5836 -0.2501  0.0353]
 [-1.1238 -2.2335 -1.2281  0.0169  0.0993]
 [ 2.731  -0.531   0.7877  0.1642 -0.6729]
 [-0.6049  0.2312  0.7883 -0.5207 -1.1542]
 [-1.7794 -1.8091 -1.2408  0.2381 -0.1468]
 [ 0.0574  1.8637 -0.9341  0.1946 -1.3434]
 [-1.3883 -1.1856 -1.132  -1.9555 -0.1374]
 [-1.6885 -0.5165  2.2578  1.1022  0.4019]
 [-1.0129  0.1949  1.3264 -1.3565 -0.2941]
 [ 0.6037 -1.7507 -1.1256 -0.162   0.3563]
 [-0.3538 -0.6424 -0.5276  0.6

In [37]:
if n_components==2:
    plt.scatter(final_result[:,0],final_result[:,1])
    plt.xlabel('Prinicpal Component 1')
    plt.ylabel('Prinicpal Component 2')
    plt.title("PCA Result")
    plt.show()

In [39]:
#step11: Compute reconstruction error(Loss)
reconstructed_data=np.dot(final_result,selected_eigenvectors.T)

#transform back to original scale
reconstructed_data_original_scale=reconstructed_data * std_dev + mean
#Calculate Mean Squared Error b/w original and reconstructed data       
mse=np.mean((data - reconstructed_data_original_scale)**2)
print("Reconstructed Loss:", mse)

Reconstructed Loss: 0.029908394118519845
